In [1]:
import numpy as np

In [2]:
A= np.array([1,2,3,4])

In [3]:
print(A)

[1 2 3 4]


In [4]:
np.ndim(A)

1

In [5]:
A.shape

(4,)

In [6]:
A.shape[0]

4

In [7]:
B=np.array([[1,2],[3,4],[5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
np.ndim(B)

2

In [9]:
B.shape

(3, 2)

In [10]:
#행렬의 곱

In [11]:
a=np.array([[1,2],[3,4]])
a.shape

(2, 2)

In [12]:
b=np.array([[5,6],[7,8]])
b.shape

(2, 2)

In [13]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [14]:
#행렬곱에 맞는 연산만을 수행 가능